/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	group_v1 "github.com/alok87/apik8s/pkg/apis/group/v1"
	clientset "github.com/alok87/apik8s/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/alok87/apik8s/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1 "github.com/alok87/apik8s/pkg/client/listers_generated/group/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// MykindInformer provides access to a shared informer and lister for
// Mykinds.
type MykindInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MykindLister
}

type mykindInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewMykindInformer constructs a new informer for Mykind type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMykindInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.GroupV1().Mykinds(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.GroupV1().Mykinds(namespace).Watch(options)
			},
		},
		&group_v1.Mykind{},
		resyncPeriod,
		indexers,
	)
}

func defaultMykindInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewMykindInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *mykindInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&group_v1.Mykind{}, defaultMykindInformer)
}

func (f *mykindInformer) Lister() v1.MykindLister {
	return v1.NewMykindLister(f.Informer().GetIndexer())
}
