/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	authentication "github.com/alok87/apik8s/pkg/apis/authentication"
	internalclientset "github.com/alok87/apik8s/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/alok87/apik8s/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/alok87/apik8s/pkg/client/listers_generated/authentication/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// TokenInformer provides access to a shared informer and lister for
// Tokens.
type TokenInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.TokenLister
}

type tokenInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewTokenInformer constructs a new informer for Token type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTokenInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.Authentication().Tokens(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.Authentication().Tokens(namespace).Watch(options)
			},
		},
		&authentication.Token{},
		resyncPeriod,
		indexers,
	)
}

func defaultTokenInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTokenInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *tokenInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&authentication.Token{}, defaultTokenInformer)
}

func (f *tokenInformer) Lister() internalversion.TokenLister {
	return internalversion.NewTokenLister(f.Informer().GetIndexer())
}
