// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1

import (
	group "github.com/alok87/apik8s/pkg/apis/group"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1_Mykind_To_group_Mykind,
		Convert_group_Mykind_To_v1_Mykind,
		Convert_v1_MykindList_To_group_MykindList,
		Convert_group_MykindList_To_v1_MykindList,
		Convert_v1_MykindSpec_To_group_MykindSpec,
		Convert_group_MykindSpec_To_v1_MykindSpec,
		Convert_v1_MykindStatus_To_group_MykindStatus,
		Convert_group_MykindStatus_To_v1_MykindStatus,
		Convert_v1_MykindStatusStrategy_To_group_MykindStatusStrategy,
		Convert_group_MykindStatusStrategy_To_v1_MykindStatusStrategy,
		Convert_v1_MykindStrategy_To_group_MykindStrategy,
		Convert_group_MykindStrategy_To_v1_MykindStrategy,
	)
}

func autoConvert_v1_Mykind_To_group_Mykind(in *Mykind, out *group.Mykind, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_MykindSpec_To_group_MykindSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_MykindStatus_To_group_MykindStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Mykind_To_group_Mykind is an autogenerated conversion function.
func Convert_v1_Mykind_To_group_Mykind(in *Mykind, out *group.Mykind, s conversion.Scope) error {
	return autoConvert_v1_Mykind_To_group_Mykind(in, out, s)
}

func autoConvert_group_Mykind_To_v1_Mykind(in *group.Mykind, out *Mykind, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_group_MykindSpec_To_v1_MykindSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_group_MykindStatus_To_v1_MykindStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_group_Mykind_To_v1_Mykind is an autogenerated conversion function.
func Convert_group_Mykind_To_v1_Mykind(in *group.Mykind, out *Mykind, s conversion.Scope) error {
	return autoConvert_group_Mykind_To_v1_Mykind(in, out, s)
}

func autoConvert_v1_MykindList_To_group_MykindList(in *MykindList, out *group.MykindList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]group.Mykind)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_MykindList_To_group_MykindList is an autogenerated conversion function.
func Convert_v1_MykindList_To_group_MykindList(in *MykindList, out *group.MykindList, s conversion.Scope) error {
	return autoConvert_v1_MykindList_To_group_MykindList(in, out, s)
}

func autoConvert_group_MykindList_To_v1_MykindList(in *group.MykindList, out *MykindList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Mykind)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_group_MykindList_To_v1_MykindList is an autogenerated conversion function.
func Convert_group_MykindList_To_v1_MykindList(in *group.MykindList, out *MykindList, s conversion.Scope) error {
	return autoConvert_group_MykindList_To_v1_MykindList(in, out, s)
}

func autoConvert_v1_MykindSpec_To_group_MykindSpec(in *MykindSpec, out *group.MykindSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1_MykindSpec_To_group_MykindSpec is an autogenerated conversion function.
func Convert_v1_MykindSpec_To_group_MykindSpec(in *MykindSpec, out *group.MykindSpec, s conversion.Scope) error {
	return autoConvert_v1_MykindSpec_To_group_MykindSpec(in, out, s)
}

func autoConvert_group_MykindSpec_To_v1_MykindSpec(in *group.MykindSpec, out *MykindSpec, s conversion.Scope) error {
	return nil
}

// Convert_group_MykindSpec_To_v1_MykindSpec is an autogenerated conversion function.
func Convert_group_MykindSpec_To_v1_MykindSpec(in *group.MykindSpec, out *MykindSpec, s conversion.Scope) error {
	return autoConvert_group_MykindSpec_To_v1_MykindSpec(in, out, s)
}

func autoConvert_v1_MykindStatus_To_group_MykindStatus(in *MykindStatus, out *group.MykindStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1_MykindStatus_To_group_MykindStatus is an autogenerated conversion function.
func Convert_v1_MykindStatus_To_group_MykindStatus(in *MykindStatus, out *group.MykindStatus, s conversion.Scope) error {
	return autoConvert_v1_MykindStatus_To_group_MykindStatus(in, out, s)
}

func autoConvert_group_MykindStatus_To_v1_MykindStatus(in *group.MykindStatus, out *MykindStatus, s conversion.Scope) error {
	return nil
}

// Convert_group_MykindStatus_To_v1_MykindStatus is an autogenerated conversion function.
func Convert_group_MykindStatus_To_v1_MykindStatus(in *group.MykindStatus, out *MykindStatus, s conversion.Scope) error {
	return autoConvert_group_MykindStatus_To_v1_MykindStatus(in, out, s)
}

func autoConvert_v1_MykindStatusStrategy_To_group_MykindStatusStrategy(in *MykindStatusStrategy, out *group.MykindStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1_MykindStatusStrategy_To_group_MykindStatusStrategy is an autogenerated conversion function.
func Convert_v1_MykindStatusStrategy_To_group_MykindStatusStrategy(in *MykindStatusStrategy, out *group.MykindStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1_MykindStatusStrategy_To_group_MykindStatusStrategy(in, out, s)
}

func autoConvert_group_MykindStatusStrategy_To_v1_MykindStatusStrategy(in *group.MykindStatusStrategy, out *MykindStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_group_MykindStatusStrategy_To_v1_MykindStatusStrategy is an autogenerated conversion function.
func Convert_group_MykindStatusStrategy_To_v1_MykindStatusStrategy(in *group.MykindStatusStrategy, out *MykindStatusStrategy, s conversion.Scope) error {
	return autoConvert_group_MykindStatusStrategy_To_v1_MykindStatusStrategy(in, out, s)
}

func autoConvert_v1_MykindStrategy_To_group_MykindStrategy(in *MykindStrategy, out *group.MykindStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1_MykindStrategy_To_group_MykindStrategy is an autogenerated conversion function.
func Convert_v1_MykindStrategy_To_group_MykindStrategy(in *MykindStrategy, out *group.MykindStrategy, s conversion.Scope) error {
	return autoConvert_v1_MykindStrategy_To_group_MykindStrategy(in, out, s)
}

func autoConvert_group_MykindStrategy_To_v1_MykindStrategy(in *group.MykindStrategy, out *MykindStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_group_MykindStrategy_To_v1_MykindStrategy is an autogenerated conversion function.
func Convert_group_MykindStrategy_To_v1_MykindStrategy(in *group.MykindStrategy, out *MykindStrategy, s conversion.Scope) error {
	return autoConvert_group_MykindStrategy_To_v1_MykindStrategy(in, out, s)
}
