/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package group

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalMykind = builders.NewInternalResource(
		"mykinds",
		func() runtime.Object { return &Mykind{} },
		func() runtime.Object { return &MykindList{} },
	)
	InternalMykindStatus = builders.NewInternalResourceStatus(
		"mykinds",
		func() runtime.Object { return &Mykind{} },
		func() runtime.Object { return &MykindList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("group.mydomain").WithKinds(
		InternalMykind,
		InternalMykindStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type Mykind struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   MykindSpec
	Status MykindStatus
}

type MykindSpec struct {
}

type MykindStatus struct {
}

//
// Mykind Functions and Structs
//
// +k8s:deepcopy-gen=false
type MykindStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type MykindStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type MykindList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []Mykind
}

func (Mykind) NewStatus() interface{} {
	return MykindStatus{}
}

func (pc *Mykind) GetStatus() interface{} {
	return pc.Status
}

func (pc *Mykind) SetStatus(s interface{}) {
	pc.Status = s.(MykindStatus)
}

func (pc *Mykind) GetSpec() interface{} {
	return pc.Spec
}

func (pc *Mykind) SetSpec(s interface{}) {
	pc.Spec = s.(MykindSpec)
}

func (pc *Mykind) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *Mykind) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc Mykind) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store Mykind.
// +k8s:deepcopy-gen=false
type MykindRegistry interface {
	ListMykinds(ctx request.Context, options *internalversion.ListOptions) (*MykindList, error)
	GetMykind(ctx request.Context, id string, options *metav1.GetOptions) (*Mykind, error)
	CreateMykind(ctx request.Context, id *Mykind) (*Mykind, error)
	UpdateMykind(ctx request.Context, id *Mykind) (*Mykind, error)
	DeleteMykind(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewMykindRegistry(sp builders.StandardStorageProvider) MykindRegistry {
	return &storageMykind{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageMykind struct {
	builders.StandardStorageProvider
}

func (s *storageMykind) ListMykinds(ctx request.Context, options *internalversion.ListOptions) (*MykindList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*MykindList), err
}

func (s *storageMykind) GetMykind(ctx request.Context, id string, options *metav1.GetOptions) (*Mykind, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*Mykind), nil
}

func (s *storageMykind) CreateMykind(ctx request.Context, object *Mykind) (*Mykind, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, false)
	if err != nil {
		return nil, err
	}
	return obj.(*Mykind), nil
}

func (s *storageMykind) UpdateMykind(ctx request.Context, object *Mykind) (*Mykind, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object, builders.Scheme))
	if err != nil {
		return nil, err
	}
	return obj.(*Mykind), nil
}

func (s *storageMykind) DeleteMykind(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
